In [8]:
import pandas as pd
import numpy as np
pd.set_option('display.width',200)#勝手に改行コードを入れられるのを防ぐ
#train_data_df=pd.DataFrame(columns=['result_com','number_race','racer_1_ID','racer_2_ID','racer_3_ID','racer_4_ID','racer_5_ID','racer_6_ID'])

In [9]:
years=['2012','2013','2014','2015','2016','2017','2018','2019','2020']

for year in years:
    train_data_df=pd.DataFrame(columns=['result_com','number_race','racer_1_ID','racer_2_ID','racer_3_ID','racer_4_ID','racer_5_ID','racer_6_ID'])
    read_resultdata_path = "asiya_result_txt/{0}_result_asiya.txt".format(year)
    write_file_path="asiya_result_csv2/asiya_result_{0}.csv".format(year)
    resultdata = open(read_resultdata_path, "r", encoding="utf-8_sig")
    money=0
    normal_race=0
    get_money=0
    for line in resultdata:
    # print(line[:12])
    # print(line[4:5]) #レースを示す"R"の入っている位置
    # print(line[3:4])#レースの番号が入っている位置
    # print(line[2:4])#着の情報が入っている位置
    # print(line[6:7])#艇番号の入っている位置
    # print(line[8:12])#登録暗号４桁の入っている位置
    # ////////////////////////////////以下レース番号の取得
        if line[4:5] == "R":
            if line[2:4]=="10":
                number_race=line[2:4]
            elif line[2:4]=="11":
                number_race=line[2:4]
            elif line[2:4]=="12":
                number_race=line[2:4]
            else:
                number_race = line[3:4]
            racer_1 = 0  # 同着レースを見つけるための印付け
            racer_2 = 0  # 同着レースを見つけるための印付け
            racer_3 = 0  # 同着レースを見つけるための印付け
# //////////////////////////////以下着順獲得
    # racer_1st=0#同着レースを見つけるための印付け
    # racer_2st=0#同着レースを見つけるための印付け
        if line[2:4] == "01":
            racer_1 = int(line[6:7])
        elif line[2:4] == "02":
            racer_2 = int(line[6:7])
        elif line[2:4] == "03":
            racer_3 = int(line[6:7])

# //////////////////////////////////以下選手の登録番号取得
        if line[6:7] == "1":
            racer_1_ID = int(line[8:12])
            racer_1_b=int(line[22:24])#ボート番号
            racer_1_m=int(line[27:29])#モータ番号
        elif line[6:7] == "2":
            racer_2_ID = int(line[8:12])
            racer_2_b=int(line[22:24])
            racer_2_m=int(line[27:29])
        elif line[6:7] == "3":
            racer_3_ID = int(line[8:12])
            racer_3_b=int(line[22:24])
            racer_3_m=int(line[27:29])
        elif line[6:7] == "4":
            racer_4_ID = int(line[8:12])
            racer_4_b=int(line[22:24])
            racer_4_m=int(line[27:29])
        elif line[6:7] == "5":
            racer_5_ID = int(line[8:12])
            racer_5_b=int(line[22:24])
            racer_5_m=int(line[27:29])
        elif line[6:7] == "6":
            racer_6_ID = int(line[8:12])
            racer_6_b=int(line[22:24])
            racer_6_m=int(line[27:29])
# //////////////////以下着順の組み合わせの選別
        if racer_1!=0 and racer_2!=0 and racer_3!=0: 
            if line[2:4] == "06":
                racers_arr=['1','2','3','4','5','6']
                result_com=0
                result_com+=(racer_1 - 1)*20
                #racers_arr=racers_arr.remove(str(racer_1))
                racers_arr.remove(str(racer_1))
                index_2=racers_arr.index(str(racer_2))
                result_com+=index_2*4
                #racers_arr=racers_arr.remove(str(racer_2))
                racers_arr.remove(str(racer_2))
                index_3=racers_arr.index(str(racer_3))
                result_com+=(index_3+1)
# /////////////////////////////////以下取り出した情報をdataframe化
     #レースの配当金の情報を追加する
        if line[8:9] == "３":
            if get_money==0:
                money=line[23:29]
                try:
                    money=int(money)
                    get_money=1
                except ValueError:
                    print('Error')
                    get_money=0
    # /////////////////////////////////以下取り出した情報をdataframe化
        if line[2:4] == "06":#フライング、事故が発生したレースを除外するために6(全員着を得ている)があるときのみ書き込み
            normal_race=1
            money=0
            get_money=0
        if (money!=0) and (normal_race==1):#フライング、事故が発生したレースを除外するために6(全員着を得ている)があるときのみ書き込み
            add_dict = {"result_com": result_com,"money":money, "number_race": number_race, "racer_1_ID": racer_1_ID, "racer_2_ID": racer_2_ID,"racer_3_ID": racer_3_ID, "racer_4_ID": racer_4_ID, "racer_5_ID": racer_5_ID, "racer_6_ID": racer_6_ID,'racer_1_b':racer_1_b,'racer_1_m':racer_1_m,'racer_2_b':racer_2_b,'racer_2_m':racer_2_m,'racer_3_b':racer_3_b,'racer_3_m':racer_3_m,'racer_4_b':racer_4_b,'racer_4_m':racer_4_m,'racer_5_b':racer_5_b,'racer_5_m':racer_5_m,'racer_6_b':racer_6_b,'racer_6_m':racer_6_m}
            add_df = pd.DataFrame(add_dict, index=[''])
            train_data_df = train_data_df.append(add_df)
            money=0
            normal_race=0
    #//////////////////////////////////////CSVファイルへ出力
    train_data_df.to_csv(write_file_path)

In [3]:
racers_arr.index(str(racer_3))

ValueError: '0' is not in list

In [7]:
line

'  06  4 4388 是\u3000澤\u3000\u3000孝\u3000宏  6   15    6.74   4    0.09      .  . \n'

In [6]:
train_data_df

,money,number_race,racer_1_ID,racer_1_b,racer_1_m,racer_2_ID,racer_2_b,racer_2_m,racer_3_ID,racer_3_b,...,racer_4_ID,racer_4_b,racer_4_m,racer_5_ID,racer_5_b,racer_5_m,racer_6_ID,racer_6_b,racer_6_m,result_com
,1060.0,2,3297,14.0,14.0,3964,2.0,23.0,5008,42.0,...,3826,60.0,12.0,3310,33.0,29.0,5084,49.0,51.0,10
,730.0,3,3712,38.0,39.0,3553,24.0,58.0,3959,46.0,...,3663,7.0,47.0,4486,30.0,27.0,5111,48.0,37.0,43
,380.0,4,3717,54.0,15.0,4057,25.0,70.0,4198,50.0,...,4703,19.0,61.0,4815,5.0,63.0,5081,16.0,13.0,2
,1340.0,5,4080,23.0,16.0,3868,37.0,68.0,2903,31.0,...,3945,34.0,45.0,3800,41.0,52.0,4292,6.0,41.0,14
,3200.0,6,4633,47.0,20.0,3522,10.0,36.0,4437,28.0,...,5029,59.0,22.0,4583,52.0,62.0,4702,58.0,57.0,25
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
,18030.0,3,3488,13.0,49.0,3614,38.0,36.0,3940,52.0,...,4811,26.0,45.0,3304,20.0,53.0,3600,45.0,66.0,25
,800.0,4,3297,33.0,38.0,4710,35.0,40.0,3164,27.0,...,3233,60.0,23.0,5092,53.0,51.0,5106,2.0,30.0,22
,730.0,5,4496,59.0,11.0,4188,46.0,29.0,3478,19.0,...,4631,12.0,70.0,4511,18.0,41.0,4033,7.0,68.0,2
,13180.0,6,3506,10.0,43.0,4988,48.0,19.0,4928,25.0,...,4834,16.0,42.0,3251,54.0,28.0,3955,30.0,39.0,19
,690.0,8,3934,17.0,61.0,4835,1.0,44.0,4106,23.0,...,5067,14.0,62.0,3297,33.0,38.0,3614,38.0,36.0,7

In [ ]:

"""
            
            
            if racer_1st == 1:
                if racer_2st == 2:
                    result_com = 1
                elif racer_2st == 3:
                    result_com = 2
                elif racer_2st == 4:
                    result_com = 3
                elif racer_2st == 5:
                    result_com = 4
                elif racer_2st == 6:
                    result_com = 5
            elif racer_1st == 2:
                if racer_2st == 1:
                    result_com = 6
                elif racer_2st == 3:
                    result_com = 7
                elif racer_2st == 4:
                    result_com = 8
                elif racer_2st == 5:
                    result_com = 9
                elif racer_2st == 6:
                    result_com = 10
            elif racer_1st == 3:
                if racer_2st == 1:
                    result_com = 11
                elif racer_2st == 2:
                    result_com = 12
                elif racer_2st == 4:
                    result_com = 13
                elif racer_2st == 5:
                    result_com = 14
                elif racer_2st == 6:
                    result_com = 15
            elif racer_1st == 4:
                if racer_2st == 1:
                    result_com = 16
                elif racer_2st == 2:
                    result_com = 17
                elif racer_2st == 3:
                    result_com = 18
                elif racer_2st == 5:
                    result_com = 19
                elif racer_2st == 6:
                    result_com = 20
            elif racer_1st == 5:
                if racer_2st == 1:
                    result_com = 21
                elif racer_2st == 2:
                    result_com = 22
                elif racer_2st == 3:
                    result_com = 23
                elif racer_2st == 4:
                    result_com = 24
                elif racer_2st == 6:
                    result_com = 25
            elif racer_1st == 6:
                if racer_2st == 1:
                    result_com = 26
                elif racer_2st == 2:
                    result_com = 27
                elif racer_2st == 3:
                    result_com = 28
                elif racer_2st == 4:
                    result_com = 29
                elif racer_2st == 5:
                    result_com = 30
"""