In [1]:
import pandas as pd
import numpy as np
from sklearn.metrics import accuracy_score
from sklearn.model_selection import cross_val_score
from matplotlib import pyplot as plt
import seaborn
from pandas import DataFrame
from tqdm import tqdm
from imblearn.under_sampling import RandomUnderSampler #アンダーサンプリング用
from sklearn.model_selection import train_test_split
import pickle
# 機械学習用
from sklearn.cluster import KMeans #クラスタリング用
from sklearn.ensemble import RandomForestClassifier#ランダムフォレスト
from copy import deepcopy as cp
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import AdaBoostClassifier
import lightgbm as lgb
from sklearn.linear_model import LogisticRegression as LR
import time
import datetime
import os #ディレクトリ作成用
import xgboost as xgb
import sys
#自作のモジュールのインポート
import module.master as master
import module.graph as graph
import module.trans_text_code as trans
import module.data_making as making

In [2]:
place_master=master.get_place_master()
for place in place_master.items():
    #print(place[0],place[1],'\n')
    place_name=place[1]
    dir_path = "../../bot_database/{place_name}/model_score_{place_name}/".format(place_name=place_name)#作成したデータの書き込み先#使用するデータの読み込み
    if os.path.exists(dir_path)==False:
        os.makedirs(dir_path)
    else:
        pass

## V1_1  クラスタリングラベルの復活

In [ ]:
#データ格納用のディレクトリ作り
version='V1_1'#学習デー加工関数のバージョン


place_master=master.get_place_master()
for place in place_master.items():
    place_name=place[1]
    ################################################========================================================================================================================
    ################################################========================================================================================================================
    ################################################========================================================================================================================
    ################################################========================================================================================================================
    #各会場の学習データの読み込みと加工
    result_filepath="../..//bot_database/{place_name}/{place_name}_train/train_{place_name}.csv".format(place_name=place_name)#作成したデータの書き込み先#使用するデータの読み込み
    result_base_df=pd.read_csv(result_filepath)
    result_base_df=result_base_df.drop(["Unnamed: 0"],axis=1)
    ################################################========================================================================================================================
    ################################################========================================================================================================================
    ################################################========================================================================================================================
    ################################################========================================================================================================================
    #バージョンごとに学習データの加工関数を変える。
    result_df=making.data_making_1_1(result_base_df)
    ################################################========================================================================================================================
    ################################################========================================================================================================================
    ################################################========================================================================================================================
    ################################################========================================================================================================================
    ################################################========================================================================================================================
    ################################################========================================================================================================================
    ################################################========================================================================================================================
    ################################################========================================================================================================================
    making.making_model_score(version,place_name,result_df)#パラメータの探索
    ################################################========================================================================================================================
    ################################################========================================================================================================================
    ################################################========================================================================================================================
    ################################################========================================================================================================================

  0%|                                                                                           | 0/28 [00:00<?, ?it/s]

kiryu

  4%|██▉                                                                               | 1/28 [02:03<55:46, 123.94s/it]

In [5]:
place='omura'
result_filepath="../..//bot_database/{place_name}/{place_name}_train/train_{place_name}.csv".format(place_name=place_name)#作成したデータの書き込み先#使用するデータの読み込み
result_base_df=pd.read_csv(result_filepath)
result_base_df=result_base_df.drop(["Unnamed: 0"],axis=1)
result_df,test_train_df,test_test_df=making.data_making_1_1(result_base_df)

In [4]:
result_df

       racer_1_rank  racer_1_age  racer_1_doub  racer_1_ave_st  racer_2_rank  racer_2_age  racer_2_doub  racer_2_ave_st  racer_3_rank  racer_3_age  ...  racer_5_male_1  racer_6_male_0  racer_6_male_1  num=3  num=5  num=7  num=9  year   money  result_com
0                 2         43.0         0.267            0.21             3         37.0         0.384            0.18             2         30.0  ...               1               0               1      1      4      5      3  2012  3330.0          41
1                 2         52.0         0.321            0.16             3         42.0         0.350            0.19             2         34.0  ...               1               0               1      0      2      2      4  2012   780.0          22
2                 2         30.0         0.108            0.23             3         39.0         0.381            0.21             2         55.0  ...               1               0               1      2      0      3      8  2012  1240.0          68
3                 2         38.0         0.242            0.22             1         26.0         0.200            0.22             2         25.0  ...               1               0               1      2      0      1      0  2012  2510.0          68
4                 3         44.0         0.459            0.18             3         57.0         0.391            0.15             3         24.0  ...               1               0               1      0      3      5      1  2012   830.0           1
...             ...          ...           ...             ...           ...          ...           ...             ...           ...          ...  ...             ...             ...             ...    ...    ...    ...    ...   ...     ...         ...
19083             3         38.0         0.390            0.16             2         40.0         0.263            0.17             2         52.0  ...               1               0               1      0      3      0      5  2020  1340.0           9
19084             2         37.0         0.212            0.16             2         40.0         0.336            0.15             2         46.0  ...               1               0               1      1      1      3      8  2020  8470.0          29
19085             4         37.0         0.423            0.14             3         53.0         0.384            0.17             2         35.0  ...               1               0               1      2      2      2      7  2020  1220.0           4
19086             3         40.0         0.449            0.13             4         41.0         0.575            0.14             3         38.0  ...               1               0               1      1      1      5      3  2020   840.0           5
19087             4         41.0         0.523            0.14             4         33.0         0.647            0.17             4         31.0  ...               1               0               1      2      2      0      5  2020  6860.0          41

[19088 rows x 55 columns]