In [1]:
#いろいろインポート
import pandas as pd
import numpy as np
from sklearn.metrics import accuracy_score
from sklearn.model_selection import cross_val_score
from matplotlib import pyplot as plt
import seaborn
from pandas import DataFrame
from tqdm import tqdm
from imblearn.under_sampling import RandomUnderSampler #アンダーサンプリング用
import pickle
# 機械学習用
from sklearn.cluster import KMeans #クラスタリング用
from sklearn.ensemble import RandomForestClassifier#ランダムフォレスト
from copy import deepcopy as cp
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import AdaBoostClassifier
import lightgbm as lgb
from sklearn.linear_model import LogisticRegression as LR

pd.set_option('display.width',400)#勝手に改行コードを入れられるのを防ぐ

In [2]:
#モデルスコアデータの読み込み
score_df = pd.read_csv('../csv/model_score.csv')
score_df=score_df.drop(["Unnamed: 0"],axis=1)#csvファイルについている名無しの列を削除
display(score_df)

       target_com  depth  target_per       総収益      投資金額    出現数   購買予測数        利益率    購買的中率    的中数
0             1.0    4.0        51.0  256020.0  314900.0  234.0  3149.0  81.302001  7.43093  234.0
1             1.0    4.0        52.0  256020.0  314900.0  234.0  3149.0  81.302001  7.43093  234.0
2             1.0    4.0        53.0  256020.0  314900.0  234.0  3149.0  81.302001  7.43093  234.0
3             1.0    4.0        54.0  256020.0  314900.0  234.0  3149.0  81.302001  7.43093  234.0
4             1.0    4.0        55.0  256020.0  314900.0  234.0  3149.0  81.302001  7.43093  234.0
...           ...    ...         ...       ...       ...    ...     ...        ...      ...    ...
57910       119.0    8.0       145.0       0.0   26400.0    1.0   264.0   0.000000  0.00000    0.0
57911       119.0    8.0       146.0       0.0    9700.0    1.0    97.0   0.000000  0.00000    0.0
57912       119.0    8.0       147.0       0.0    9700.0    1.0    97.0   0.000000  0.00000    0.0
57913       119.0    8.0       148.0       0.0    9700.0    1.0    97.0   0.000000  0.00000    0.0
57914       119.0    8.0       149.0       0.0    9700.0    1.0    97.0   0.000000  0.00000    0.0

[57915 rows x 10 columns]

#### モデル性能評価用のデータフレーム作成(result_comごとの閾値を持つ)

In [3]:
#学習データの読み込み
result_df = pd.read_csv('../csv/train_asiya.csv')
result_df=result_df.drop(["Unnamed: 0"],axis=1)#csvファイルについている名無しの列を削除

df=result_df
#学習、テストデータ切り分け
num_data = len(df) 
num_valid = int(num_data/6.0)
valid_df = df.loc[(num_data-num_valid):num_data, :]#なるべく最新のデータを未知データに
train_df = df.loc[0:(num_data-num_valid-1), :]
train_money=pd.Series(train_df['money'])
valid_money=pd.Series(valid_df['money'])
#出現数の分布
result_com_s=valid_df['result_com'].value_counts()
result_com_s=result_com_s.sort_index()
gain_mean=valid_df.groupby('result_com')['money'].mean()
gain_mean=gain_mean.sort_index()

gain_median=valid_df.groupby('result_com')['money'].median()
gain_median=gain_median.sort_index()
result_com_df=pd.DataFrame({'result_com':result_com_s.index,
                            'result_com_num':result_com_s.values,
                            'result_com_per':result_com_s.values/sum(result_com_s.values)*100,
                            'gain_mean':gain_mean.values,
                            'gain_median':gain_median.values,})
display(result_com_df)

     result_com  result_com_num  result_com_per     gain_mean  gain_median
0           1.0             234        7.430930   1094.102564        785.0
1           2.0             204        6.478247   1280.196078        930.0
2           3.0             145        4.604636   2087.103448       1350.0
3           4.0              89        2.826294   2414.943820       1610.0
4           5.0             180        5.716100   1319.111111        950.0
..          ...             ...             ...           ...          ...
112       115.0               2        0.063512  10300.000000      10300.0
113       116.0               2        0.063512  21955.000000      21955.0
114       117.0               3        0.095268  34193.333333      42250.0
115       118.0               3        0.095268  18846.666667       8670.0
116       119.0               1        0.031756  53210.000000      53210.0

[117 rows x 5 columns]

### モデル性能評価機能

In [5]:
#基準をクリアしたモデルを格納するdf
depths_arr=[4,5,6,7,8]
model_para_df=pd.DataFrame(columns=['target_com','depth','target_per','総収益', '投資金額','出現数','購買予測数','利益率','購買的中率','的中数'])
for target_com in result_com_df['result_com'].values:
    target_com_df=score_df[score_df['target_com']==target_com]
    #閾値の作成===============================================================
    gain_th=110#利益率の閾値
    result_s=result_com_df[result_com_df['result_com']==target_com]
    buy_accuracy_th=result_s['result_com_per'].values[0]*1.1#買ったうちの的中率の閾値
    num_tp_th=result_s['result_com_num'].values[0]*0.2#あたった回数の閾値(出現回数の20%が的中)
    
    diff_gain_th=108#利益率の閾値
    diff_buy_accuracy_th=result_s['result_com_per'].values[0]*1.1#前後モデルの買ったうちの的中率の閾値
    diff_num_tp_th=result_s['result_com_num'].values[0]*0.13#前後モデルのあたった回数の閾値(出現回数の20%が的中)
    
    #==========================================================
    for target_depth in depths_arr:
        target_com_depth_df=target_com_df[target_com_df['depth']==target_depth]
        
        len_df=len(target_com_depth_df)
        df=target_com_depth_df.copy()
        df['number_i']=np.arange(0,len_df,1)
        
        for _, row in df.iterrows():
            if ((row['number_i']==0) or (row['number_i']==1) or (row['number_i']==len_df-2) or (row['number_i']==len_df-1)):
                pass
            else:
                #前後のモデルのスコア===================================
                diff_m2_row=df[df['number_i']==(row['number_i']-2)]
                diff_m1_row=df[df['number_i']==(row['number_i']-1)]
                diff_p1_row=df[df['number_i']==(row['number_i']+1)]
                diff_p2_row=df[df['number_i']==(row['number_i']+2)]
                diff_models=[diff_m2_row,diff_m1_row,diff_p1_row,diff_p2_row]
                #===================================================
                if ((row['利益率']>gain_th) and (row['購買的中率']>buy_accuracy_th) and (row['的中数']>=num_tp_th)):#初めに真ん中のモデルの性能評価
                    #前後モデルの評価
                    flag_arr=[0,0,0,0]
                    for index in range(len(flag_arr)):

                        diff_model=diff_models[index].iloc[0,:]
                        if ((diff_model['利益率']>diff_gain_th) and (diff_model['購買的中率']>diff_buy_accuracy_th) and (diff_model['的中数']>=diff_num_tp_th)):#前後モデルの性能評価
                            flag_arr[index]=1
                        else:
                            pass
                    if sum(flag_arr)==4:
                        model_para_df=model_para_df.append(row)
                        
                else:
                    pass

In [6]:
model_para_df

       target_com  depth  target_per       総収益     投資金額    出現数  購買予測数         利益率      購買的中率   的中数  number_i
1258          3.0    6.0       121.0   24350.0  20300.0  145.0  203.0  119.950739  15.763547  32.0      70.0
1862          4.0    7.0       131.0   31920.0  28300.0   89.0  283.0  112.791519  10.247350  29.0      80.0
5999         13.0    4.0       110.0   76970.0  59000.0   84.0  590.0  130.457627   5.084746  30.0      59.0
6000         13.0    4.0       111.0   61030.0  52800.0   84.0  528.0  115.587121   5.303030  28.0      60.0
6096         13.0    5.0       108.0  109840.0  89600.0   84.0  896.0  122.589286   4.687500  42.0      57.0
...           ...    ...         ...       ...      ...    ...    ...         ...        ...   ...       ...
56520       117.0    4.0       141.0   57400.0  38000.0    3.0  380.0  151.052632   0.263158   1.0      90.0
56616       117.0    5.0       138.0   57400.0  48400.0    3.0  484.0  118.595041   0.206612   1.0      87.0
56617       117.0    5.0       139.0   57400.0  48400.0    3.0  484.0  118.595041   0.206612   1.0      88.0
56618       117.0    5.0       140.0   57400.0  48700.0    3.0  487.0  117.864476   0.205339   1.0      89.0
56619       117.0    5.0       141.0   57400.0  48700.0    3.0  487.0  117.864476   0.205339   1.0      90.0

[2341 rows x 11 columns]

In [7]:
model_para_df.to_csv('../csv/good_score_model.csv', encoding='utf_8_sig')

In [33]:
diff_model

(1047, target_com        3.000000
 depth             4.000000
 target_per      108.000000
 総収益           38850.000000
 投資金額          46200.000000
 出現数             145.000000
 購買予測数           462.000000
 利益率              84.090909
 購買的中率             9.523810
 的中数              44.000000
 number_i         57.000000
 Name: 1047, dtype: float64)

In [17]:
len_df

99

In [34]:
type(diff_model)

tuple